poor:poor.cpp
	g++ $^ -o $@ -lpthread
thpool:thpool.c
	g++ $^ -o $@ -lpthread
RQ:RQ.c
	g++ $^ -o $@ -lpthread
sem:sem.c
	gcc $^ -o $@ -lpthread
con_pro:con_pro.c
	g++ $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
test:test.c
	gcc $^ -o $@ -lpthread
create:create.c
	gcc $^ -o $@ -lpthread
